pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Ramyakhegde/Cucumber-Selenium-CI.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("cucumber-test")
                }
            }
        }

        stage('Run Tests in Docker') {
            steps {
                script {
                    dockerImage.run()
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/**/*', allowEmptyArchive: true
        }
    }
}
